### ISSUE TITLE
Issue updating sendgrid_template_version resource -> active field

### ISSUE THREAD

**Issue by isaaclong** [anna-money/terraform-provider-sendgrid#5]
Hello - I tried using this provider with a basic test sendgrid account with 1 template and 2 template versions. I tried changing the active version from one to the other by just setting active to 1 on the inactive version (see attached output). The apply completes successfully but that change is not reflected in the sendgrid account, and running apply again and refreshing confirms that the change wasn't applied. Is this a known problem, and is there anyone that could help look into it (or maybe there are workarounds)? From what else I have tested, all the other fields we were interested seem to be changeable and work fine (template name, template version name, template version html, template version subject) 

```
isaac.long@B-V5Q7RYQFTF:~/Desktop/sg_terraform_annamoney
  % terraform apply
sendgrid_template.isaac-dev-template-1: Refreshing state... [id=d-d126618b468e4705bae5aa42525ee15f]
sendgrid_template_version.restaurant: Refreshing state... [id=8ad600e9-f00b-4959-ab0b-d3e2933d2021]
sendgrid_template_version.realestate: Refreshing state... [id=5549fa0d-a26c-4b5e-a83c-125f179e2166]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # sendgrid_template_version.restaurant will be updated in-place
  ~ resource "sendgrid_template_version" "restaurant" {
      ~ active                 = 0 -> 1
        id                     = "8ad600e9-f00b-4959-ab0b-d3e2933d2021"
        name                   = "restaurant-version-CHANGED"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

sendgrid_template_version.restaurant: Modifying... [id=8ad600e9-f00b-4959-ab0b-d3e2933d2021]
sendgrid_template_version.restaurant: Modifications complete after 2s [id=8ad600e9-f00b-4959-ab0b-d3e2933d2021]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Also, this looks very similar to this provider source https://github.com/Trois-Six/terraform-provider-sendgrid which has been archived on github. I actually tried that source first and ran into the same issue, so thought I'd also try this one. If this isn't actively maintained, do you by any chance know of any 'official' or actively maintained community source for a sendgrid terraform provider? I have only tried these two so far (found on terraform's provider search). Let me know if I can provide any further details, thanks

![Screenshot 2023-02-22 at 2 46 22 PM](https://user-images.githubusercontent.com/87053447/220778286-45e34124-a5c3-4564-8c38-6dc31c08cdd0.png)

**Comment by arslanbekov** [comment]
Hi @isaaclong.

Yes, indeed this repository is a fork of the above, we forked it to add support for adding users from SAML since the main repository did not accept our merge as it was out of date.

Unfortunately, we do not invest time in maintaining this provider, since we do not have enough time for this, we will be glad to receive any help.
